from api import *
from config import *
from algorithms import *
from colorama import Fore
import sys
import time

def trade():
    open = False # check market open
    trading = ['AMZN', 'AAPL', 'TSLA'] # symbols to trade
    stocks = dict() # associate symbols to price history
    for sym in trading:
        # get price history for each symbol
        stocks[sym] = [get_old_prices(sym), None, 0] 
        # stock object (to classify): stock symbol links to a list which contains:
        # price, complicated three-way boolean, bought price
        # complicated three-way boolean means:
        # None: day has started, buy phase
        #  1: bought stock, holding
        # -1: sold stock, done with this for the day
    while True:
        market = get_clock() # RTC market-relative
        if not oneminleft(market): # check if one minute left
            for sym in stocks:
                stocks[sym][0].append(get_price(sym)) # get current price
            if market['is_open']:
                open = True # mark market as 'open'
                for sym in stocks:
                    # for each stock, check to buy or sell.
                    consensus = buyorsell(sym, stocks)
                    if consensus == 1 and (stocks[sym][1] != 1 and stocks[sym][1] != -1):
                        # if algorithm buys and stock is NOT owned AND NOT sold
                        stocks[sym][2] = get_price(sym) # save current price for profit
                        buy(sym, 5) # buy $5 worth
                        stocks[sym][1] = 1 # mark buy status
                    elif (consensus == -1 and stocks[sym][1] is not None) or get_price(sym) <= stocks[sym][2] * 0.97:
                        sell(sym, stocks[sym][2]) # sell EVERYTHING (error, wrong.)
                        stocks[sym][1] = -1 # mark as sold
                    else:
                        # print stock statuses not generated by buy/sell functions
                        if stocks[sym][1] == 1:
                            print(Fore.CYAN + sym + Fore.RESET, end=' ')
                        elif stocks[sym][1] == -1:
                            print(Fore.RED + sym + Fore.RESET, end=' ')
                        else:
                            print(Fore.YELLOW + sym + Fore.RESET, end=' ')
                print() # print newline
            else: 
                if not open: 
                    # loop on market closed (program starts on market open)
                    print(Fore.RED + "Market is closed. WAITING..." + Fore.RESET)
                else:
                    # End Of Day report
                    print(Fore.CYAN + "Market closed for today. Finished up.")
                    print(Fore.GREEN + "Cash: $" + get_cash() + Fore.RESET)
                    sys.exit()
        time.sleep(60*5) # halt for 5 minutes
        
if __name__ == "__main__":
    trade()